blank_issues_enabled: true
contact_links:
  - name: FAQ
    url: https://github.com/CertifaiAI/CertifAI-Knowledge-Base/wiki
    about: "Please check your questions/issues here. Your questions may already have been answered. \U0001F642"

