name: Issues Auto Comment

on:
  issues:
    types:
      - opened

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: bubkoo/auto-comment@v1.0.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpenedReactions: 'hooray, +1'
          issuesOpenedComment: >
            👋 @{{ author }}
            
            Thank you for raising an issue. We will investigate into the matter and get back to you as soon as possible.
            
            Please make sure you have given us as much context as possible.