name: Auto Create PR

on:
  push:
    branches: faris_auto_pr # Branch will be automatically created once automated copy workflow from Classifai_FrontEnd is triggered

jobs:
  PR:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repos
        uses: actions/checkout@v2

      - name: Pre-processing PR title
        id: string
        run: |
          STRING="${{ github.event.head_commit.message }}"
          STRING="${STRING/:lipstick: Compiled codes from https:\/\/github.com\//https:\/\/api.github.com\/repos\/}"
          STRING="${STRING/pull/pulls}"
          echo "::set-output name=pr_title::$(curl -H "Accept: application/vnd.github.v3+json" ${STRING} 2>/dev/null | jq -r ".title")"    

      - name: Create PR request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          destination_branch: "v2_alpha" # Base Branch which changes will be applied to                     
          pr_title: "From classifai_frontend to classifai's webroot - ${{ steps.string.outputs.pr_title }}" # Set title for the PR
          pr_body: | # PR's body
            ## This is an automatically created PR :robot::robot:
            
            - It will triggered once codes in [***dist folder***][3] from repo [***Classifai_FrontEnd***][1] has been pushed.
            - Files & sub-folder in [***dist folder***][3] of repo [***Classifai_FrontEnd***][1] will be copied into [***classifai's webroot***][2]
            - Committed frontend PR's URL can be found in the commit history below.

            [1]: https://github.com/CertifaiAI/Classifai_FrontEnd
            [2]: https://github.com/CertifaiAI/classifai/tree/v2_alpha/classifai-core/src/main/resources/webroot
            [3]: https://github.com/CertifaiAI/Classifai_FrontEnd/tree/main/dist/classifai

          pr_reviewer: "codenamewei,devenyantis"  # Reviewer(s), can be Comma-separated list (no spaces)                                            
          pr_label: "auto-pr" # Set label for the PR                              
          pr_allow_empty: true # Creates pull request even if there are no changes

          # Further reference from https://github.com/repo-sync/pull-request
                             
